import json
from fastapi import APIRouter, Depends, HTTPException, status
import requests
from sqlalchemy import delete, insert, select, update
from sqlalchemy.ext.asyncio import AsyncSession
from auth.database import get_async_session
from dto import dto as DTO
from models.models import *
import random

orderRouter = APIRouter()
TOKEN = '6937107637:AAFarU8swL-mp7oLC0sMz44A7-F3q0QuD4Y'

def generate_order_id():
    """Generates a unique order ID."""
    return random.randint(10000000, 99999999)

@orderRouter.post("/")
async def order_add(orederDTO: DTO.Order, chatID: int | None = None, session: AsyncSession = Depends(get_async_session)):
    try:
        async with session:
            query = insert(Order).values(orederDTO.model_dump())
            await session.execute(query)
            await session.commit()
            orderItems = orederDTO.items
                
            # text_for_send = f"–°–ø–∞—Å–∏–±–æ –∑–∞ –∑–∞–∫–∞–∑!\n\n–í–∞—à –∑–∞–∫–∞–∑ ‚Ññ{order_id} –≤ –æ–±—Ä–∞–±–æ—Ç–∫–µ.\n –ë—É–¥–µ—Ç –≥–æ—Ç–æ–≤ —á–µ—Ä–µ–∑ 18 –º–∏–Ω—É—Ç.\n\n–û–ø–ª–∞—Ç–∞: {orederDTO.payment}\n\n‚ùó–ó–ê–ë–†–ê–¢–¨ –°–ê–ú–û–°–¢–û–Ø–¢–ï–õ–¨–ù–û‚ùó\n\nüìç–ê–¥—Ä–µ—Å: {orederDTO.address}\n\n–ó–∞–∫–∞–∑:\n{"".join([f"{item['count']} - {item['foodName']} - {item['price']} —Ä—É–±." for item in orderItems])}\n"
            text_for_send = f"–°–ø–∞—Å–∏–±–æ –∑–∞ –∑–∞–∫–∞–∑!\n\n–í–∞—à –∑–∞–∫–∞–∑ ‚Ññ{orederDTO.number} –≤ –æ–±—Ä–∞–±–æ—Ç–∫–µ.\n–ë—É–¥–µ—Ç –≥–æ—Ç–æ–≤ —á–µ—Ä–µ–∑ 18 –º–∏–Ω—É—Ç.\n\n–û–ø–ª–∞—Ç–∞: {orederDTO.payment}\n\n‚ùó–ó–ê–ë–†–ê–¢–¨ –°–ê–ú–û–°–¢–û–Ø–¢–ï–õ–¨–ù–û‚ùó\n\nüìç–ê–¥—Ä–µ—Å: {str(orederDTO.address)}\n\n–ó–∞–∫–∞–∑:\n" + "".join([f"{item['count']}   x   {item['foodName']}    {item['price']} —Ä—É–±.\n" for item in orderItems]) + f"\n\n–ò—Ç–æ–≥–æ: {orederDTO.total}\n\nüíÆüçú"
            requests.get(f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={chatID}&text={text_for_send}")
            return {"message": "Order added successfully"}
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))

@orderRouter.get("/")
async def order_get(session: AsyncSession = Depends(get_async_session)):
    try:
        async with session:
            query = select(Order)
            result = await session.execute(query)
            data = result.scalars().all()
            return data
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))
